logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:h2orderdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
