logging:
  level:
#    org:
#      hibernate:
#        SQL: DEBUG
    ch:
      wesr: DEBUG
#        starter:
#          kirkesampleapp: DEBUG
  datasource:
    url: jdbc:h2:mem:h2orderdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

kirke:
#  event: solace
  event: inline

solace:
  java:
    host: tcp://mds-pubsubplus:55554
    msgVpn: default
    clientUsername: default
    clientPassword: default
