logging:
  level:
#    org:
#      hibernate:
#        SQL: DEBUG
    ch:
      wesr:
        starter:
          kirkesampleapp: DEBUG
    org.springframework.cloud: DEBUG
    ch.wesr.starter.kirkespringbootstarter: DEBUG
    com.solace.spring.cloud: DEBUG

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:h2orderdb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  cloud:
    function:
      definition: eventSourceConsumer
    stream:
      default-binder: solace
      bindings:
        eventSourceConsumer-in-0:
          destination: 'try-me'


solace:
  java:
    host: localhost:55554
    client-name: default
    client-password: default
    msg-vpn: default


