POST http://localhost:8080/api/foodcart/create
Content-Type: application/json; charset=utf-8
Accept: application/json
Cache-Control: no-cache

{
  "foodCartId": "6bf9a23d-487c-42dc-93ee-d73c6153a8f6"
}

####

POST http://localhost:8080/api/foodcart/product/add
Content-Type: application/json; charset=utf-8
Accept: application/json
Cache-Control: no-cache

{
  "foodCartId": "6bf9a23d-487c-42dc-93ee-d73c6153a8f6",
  "productId": "044619bc-146e-4065-a4b8-34ed49d8b76a",
  "quantity": 1
}

####

POST http://localhost:8080/api/foodcart/confirm
Content-Type: application/json; charset=utf-8
Accept: application/json
Cache-Control: no-cache

{
  "foodCartId": "6bf9a23d-487c-42dc-93ee-d73c6153a8f6"
}
####

GET http://localhost:8080/api/foodcart/6bf9a23d-487c-42dc-93ee-d73c6153a8f6
Content-Type: application/json; charset=utf-8
Accept: application/json
Cache-Control: no-cache
